import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://in-qa.pwa.kfc.dev/');
  await page.locator('#startOrderItemButton').click();
  await page.getByTestId('disposition-order-click-handler-Disposition - Delivery').click({ timeout: 80000 });
  //await page.getByTestId('use-my-location').click();
  await page.getByTestId('store-search-input').click({ timeout: 80000 });
  await page.getByTestId('store-search-input').fill('nadau');
  await page.getByText('Nadaun, Himachal Pradesh, India', { exact: true }).click({ timeout: 80000 });
  await page.getByTestId('btn-confirm').click({ timeout: 120000 }); 
  await page.getByTestId('btn-confirm').dblclick({ timeout: 120000 }); 
  await page.locator('confirm-button-handler').click();
  await page.locator('#category-name-CAT158').getByTestId('category-click-test').click();
  await page.locator('add-to-cart-A-32050-0').click();
  await page.getByRole('button', { name: 'Close' }).click();
  await page.getByTestId('navigation-checkout-desktop').click();
  await page.getByTestId('address-field').click();
  await page.getByTestId('address-field').fill('4444');
  await page.getByTestId('continue-as-a-gust').click();
  await page.getByTestId('Full Name-masktextlabel-id').click();
  await page.getByTestId('enter-Full Name-details').press('CapsLock');
  await page.getByTestId('enter-Full Name-details').fill('D');
  await page.getByTestId('enter-Full Name-details').press('CapsLock');
  await page.getByTestId('enter-Full Name-details').fill('Disha');
  await page.getByTestId('email-masktextlabel-id').click();
  await page.getByTestId('enter-email-details').fill('disha@test.com');
  await page.getByTestId('phoneNumber-masktextlabel-id').click();
  await page.getByTestId('enter-phoneNumber-details').fill('9163527676');
  await page.getByTestId('pay-button').click();
  await page.locator('div:nth-child(3) > .payment-option-header').click();
  await page.getByTestId('continue-to-payment-btn').click();
  await page.goto('https://in-uat.pwa.kfc.dev/payment-success');
});